# Generated by Django 6.0.5 on 2026-05-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='numbre_in_stock',
            new_name='number_in_stock',
        ),
    ]
